Repository justKevv/Achievement-System, pull requests merged in 2024-12, with the labels that each got.

#11 refactor: added folder assets for better folder structure
  public/assets/icons/log-out.png
  public/assets/icons/notification.png
  public/assets/images/404_img.png
  public/assets/images/logo.png
Labels: enhancement

#13 fix: Update the Front-End logic
  resources/views/components/404.html
  resources/views/components/navbar.html
  resources/views/login.html
Labels: enhancement, fix

#14 refactor: Added namespace to ErrorHandler and View
  app/ErrorHandler.php
  app/View.php
Labels: enhancement, fix

#19 Refactor: Navbar Styling, Login Form Update, and Routing Simplification
  public/assets/images/logo-sars.png
  public/assets/images/logo.png
  resources/css/navbar.css
  resources/views/components/navbar.html
  resources/views/login.html
  routes/route.php
Labels: fix

#20 Refactor: Namespace Integration, Slim Framework Adoption, and Database Enhancements
  .gitignore
  app/Controller/Controller.php
  app/Controller/UserController.php
  app/Models/Model.php
  app/Models/User.php
  composer.json
  composer.lock
  config/config.php
  config/database.php
  database/DatabaseSeeder.php
  public/index.php
  routes/app.php
  routes/web.php
Labels: enhancement, fix

#21 feat: add .env.example and README.md for project setup and configurat…
  .env.example
  README.md
Labels: documentation

#22 feat: update autoload configuration to include Config namespace
  composer.json
Labels: enhancement

#24 feat: implement user authentication and dashboard routing with session management
  app/Controller/UserController.php
  resources/views/components/404.html
  resources/views/components/navbar.html
  resources/views/dashboard.php
  resources/views/pages/home.php
  resources/views/pages/rank.php
  resources/views/pages/submission.php
  routes/web.php
Labels: enhancement, fix

#25 feat: implement dynamic page loading and refactor dashboard routing
  resources/js/load-page.js
  resources/views/components/navbar.html
  resources/views/dashboard.php
  resources/views/login.html
  resources/views/pages/home.php
  resources/views/pages/rank.php
  resources/views/pages/submission.php
  routes/web.php
Labels: enhancement, fix

#26 fix: change history push to replace for better navigation handling
  resources/js/load-page.js
Labels: enhancement, fix

#28 feat: add .htaccess files for URL rewriting and update README to reflect Apache server requirement
  .htaccess
  README.md
  public/.htaccess
Labels: enhancement, fix

#29 feat: update .htaccess for improved URL handling and clean up navbar event listeners
  .htaccess
  resources/views/components/navbar.html
Labels: fix

#30 log in
  public/assets/images/Success factors-amico (1) 1.png
  resources/css/adminHome.css
  resources/css/loginpage.css
  resources/css/navbar.css
  resources/views/components/navbar.html
  resources/views/loginpage.html
  resources/views/pages/home.php
  resources/views/pages/rank.php
Labels: enhancement

#33 Refactor: navbar and dashboard for role-based access control and update file extensions
  resources/views/components/navbar.php
  resources/views/dashboard.php
  resources/views/pages/home.php
Labels: enhancement

#46 Enhance Navbar and Integrate Chairman Role Functionality
  app/Controller/UserController.php
  app/Models/Achievement.php
  app/Models/Chairman.php
  public/assets/css/navbar.css
  public/assets/js/modalAdd.js
  resources/views/components/navbar.php
  resources/views/pages/user.php
Labels: enhancement, fix

#53 Enhance Achievement Workflow, Dashboard Data, and Profile Management
  app/Controller/AchievementController.php
  app/Controller/DashboardController.php
  app/Controller/ProfileController.php
  app/Controller/UserController.php
  app/Models/Achievement.php
  app/Models/AchievementFile.php
  app/Models/Admin.php
  app/Models/BaseModel.php
  app/Models/Chairman.php
  app/Models/Student.php
  app/Models/User.php
  app/Models/Verification.php
  app/Services/AchievementService.php
  public/assets/css/approval.css
  public/assets/css/modal.css
  public/assets/css/submission.css
  public/assets/css/user.css
  public/assets/icons/approved.png
  public/assets/icons/rejected.png
  public/assets/js/approvalModal.js
  public/assets/js/load-page.js
  public/assets/js/modalAdd.js
  public/assets/js/submissionModal.js
  resources/views/components/navbar.php
  resources/views/dashboard.php
  resources/views/pages/approval.php
  resources/views/pages/home.php
  resources/views/pages/profile.php
  resources/views/pages/rank.php
  resources/views/pages/submission.php
  resources/views/pages/user.php
  routes/web.php
Labels: documentation, enhancement, fix
